modLoader="javafml"
loaderVersion="[41,)"
license="Apache-2.0"
issueTrackerURL="https://infernalstudios.org/foodeffects/issues"

[[mods]]
modId = "foodeffects"
version="${file.jarVersion}"
displayName = "Food Effects"
updateJSONURL="https://infernalstudios.org/api/mods/foodeffects/forge"
displayURL="https://infernalstudios.org"
logoFile = "Food_Effects_Logo.png"
credits = "See the description!"
authors = "Infernal Studios"
description = '''
Food Effects aims to re-balance Minecraft's various food items by giving each of them unique Effects upon consumption.
You can edit what food gives what effect, the duration of that effect, and the amplifier/level of the effect in the config!

Credits
HellionGames, SwanX1 - Developer
Nekomaster1000 - Conceptualiser, Artist
Orilly, Pugz - Legacy Developers
'''

[[dependencies.foodeffects]]
  modId="forge"
  mandatory=true
  versionRange="[41,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.foodeffects]]
  modId="minecraft"
  mandatory = true
  versionRange = "[1.19,1.20)"
  ordering = "NONE"
  side="BOTH"
