modLoader="javafml" 
loaderVersion="[35,)" 
license="Team Novus, All rights reserved"

[[mods]]
    modId = "novus_foodeffects"
    version = "1.0.0"
    
    logoFile = "logo.png"
    authors = "Team Novus"
    credits = "Thanks to Orilly, Pugz, and Nekomaster1000"
    displayName = "Food Effects"
    description = '''This mod aims to re-balance Minecraft's various food items.'''

[[dependencies.novus_foodeffects]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.4,1.16.5)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.novus_foodeffects]]
    modId = "forge"
    mandatory = true
    versionRange = "[35.1.4,)"
    ordering = "NONE"
    side = "BOTH"